### ISSUE TITLE
Unable to uninstall application

### ISSUE THREAD

**Issue by laiti** [macherel/Barcode-Wallet#14]
Hi,

I installed the app on my Venu 2 and configured according instructions; added token and some barcodes. I got the message "No barcode." I went to settings, switched "debug" on and went back to the app. The app [showed only the IQ logo with exclamation mark](https://laiti.fi/venu2_barcode_error.jpeg).

Then I tried to make an attempt to uninstall and reinstall the application but it seems that I am [unable to uninstall it. The uninstall button just disappears and software stays both in Connect IQ list and watch.](https://laiti.fi/venu2_barcode_uninstall.mp4)

I am using Garmin Venu 2 with the latest available updates and Google Pixel 6 running Android 12 with latest patches. I have the latest versions of Connect and Connect IQ softwares.

The app was updated successfully from 1.8.5 to 1.8.6 at some point but still uninstall does not work.

**Comment by laiti** [comment]
I managed to broke this again; it seems that if I do any change to the settings of this software via Connect IQ, I get the exclamation mark error and I need to reinstall. Changes made in Garmin Express work OK.

**Comment by macherel** [comment]
You're right, there was a major issue for some users when they change settings. I hope it is now fixed in the version 2.0.0. (please see #18 )

Regarding the uninstalling issue, you're unfortunately not the only one to whom this happens and I can't do anything for that. (Un)Installing apps is managed by Garmin software and , fortunately (for security reasons), I can't do anything to avoid uninstalling an app.
It seems there is a workaround using Connect Express PC (https://forums.garmin.com/developer/connect-iq/f/discussion/7966/user-unable-to-uninstall-device-app)
